### ISSUE TITLE
Hey 👋🏼 

### ISSUE THREAD

**Issue by simonhamp** [AkhilTreblle/custom-import#1]
Hi there. I noticed that you've forked [Laravel Nova CSV Import package](https://github.com/simonhamp/laravel-nova-csv-import)

I'm genuinely flattered and pleased to see others building on top of my work 😊

As it's MIT-licensed, it's permissive enough for you to do _almost_ whatever you want with it.

However, the one exception I take is that you have removed the original copyright notice and thus have not respected the license agreement, specifically:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Please reinstate the original copyright notice**

This can be extended to include your own name once you have a copyright claim to any code written within, but you must not remove the previous copyright notices.

For reference, you can [see the original LICENSE file here](https://github.com/simonhamp/laravel-nova-csv-import/blob/main/LICENSE.md).

I've had a quick look through the project and so far (aside of some name, email address and URL changes) it is verbatim the `laravel-nova-csv-import` package, so I believe this currently qualifies as "substantial portions of the software".

I can see that you've listed your version as a package on [Packagist already](https://packagist.org/packages/akhil-treblle/csv-import), so I guess you plan to redistribute your version.

I don't want to discourage you from developing this package further or from redistributing your modifications either - in fact, I look forward to seeing how you evolve this for your specific needs and will be happy to help you achieve them.

However, I would strongly discourage you from distributing an _identical_ package for a number of reasons:

1. It's disingenuous to the open source movement and community
2. It will potentially lead to confusion for other developers

Of course, I would also welcome your involvement in developing `laravel-nova-csv-import` rather than splintering efforts, if you're open to that.

Thank you for your time 🙏🏼 

Simon
Creator of Laravel Nova CSV Import

**Comment by AkhilTreblle** [comment]
Hi sir,

I am a big fan of yours, and I don't want to cause any trouble for you. I
encountered an issue with your package, as I needed to customize it to meet
my company's specific requirements. I tried various approaches, and
eventually, I decided to create a modified version by removing certain
mappings, setting my own resources without a dropdown, and using empty
strings instead of null values. I made these changes for my own project,
and I don't intend for this to cause any inconvenience or problems for you.
I apologize for any inconvenience caused.

**Comment by AkhilTreblle** [comment]
License updated.

**Comment by simonhamp** [comment]
Thanks @AkhilTreblle

It's no inconvenience, I just want to make sure that recognition of the hard work of other engineers like yourself isn't lost 🙂 

Please feel free to [raise any issues directly](https://github.com/simonhamp/laravel-nova-csv-import/issues) and if you implement any features that you feel are worth sharing with the community, I'd be more than happy to receive PRs. You'll be credited for your contributions, which thousands of other engineers will see.

Side note: If this is for your employer, it might be best (from a security and legal perspective for them) to host any custom packages privately rather than on a public directory like Packagist.

I'd also recommend that repos are stored privately under the organisation on GitHub, rather than publicly on an individual's account.
